// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mover} from '../models';
import {database} from '../models';
import {backend} from '../models';

export function BatchMove(arg1:Array<mover.MoveItem>,arg2:string):Promise<mover.BatchResult>;

export function BatchMoveJSON(arg1:string,arg2:string):Promise<mover.BatchResult>;

export function BatchSearch(arg1:Array<string>,arg2:number):Promise<Array<backend.SearchResult>>;

export function DbGetVideo(arg1:string):Promise<database.VideoData>;

export function DbListVideos():Promise<Array<database.VideoData>>;

export function DbUpdateVideo(arg1:string,arg2:string):Promise<void>;

export function GetOperation(arg1:string):Promise<mover.OperationLog>;

export function GetPreferences():Promise<backend.Preferences>;

export function IdentifyStudio(arg1:string):Promise<backend.StudioInfo>;

export function ListOperations():Promise<Array<mover.OperationLog>>;

export function ListStudios():Promise<Array<string>>;

export function MoveDir(arg1:string,arg2:string,arg3:string):Promise<mover.MergeResult>;

export function MoveFile(arg1:string,arg2:string,arg3:string):Promise<mover.MoveResult>;

export function PythonSearch(arg1:string):Promise<backend.SearchResult>;

export function ResetPreferences():Promise<void>;

export function RollbackLast():Promise<mover.BatchResult>;

export function RollbackOperation(arg1:string):Promise<mover.BatchResult>;

export function ScanDirectory(arg1:string,arg2:number,arg3:boolean):Promise<Array<backend.ScanResult>>;

export function UpdatePreferences(arg1:backend.Preferences):Promise<void>;
