// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConflicts(arg1) {
  return window['go']['backend']['App']['CheckConflicts'](arg1);
}

export function CheckDirConflicts(arg1) {
  return window['go']['backend']['App']['CheckDirConflicts'](arg1);
}

export function BatchMove(arg1, arg2) {
  return window['go']['backend']['App']['BatchMove'](arg1, arg2);
}

export function BatchMoveDirs(arg1, arg2) {
  return window['go']['backend']['App']['BatchMoveDirs'](arg1, arg2);
}

export function BatchMoveJSON(arg1, arg2) {
  return window['go']['backend']['App']['BatchMoveJSON'](arg1, arg2);
}

export function BatchSearch(arg1, arg2) {
  return window['go']['backend']['App']['BatchSearch'](arg1, arg2);
}

export function CancelOperation() {
  return window['go']['backend']['App']['CancelOperation']();
}

export function DbGetVideo(arg1) {
  return window['go']['backend']['App']['DbGetVideo'](arg1);
}

export function DbListVideos() {
  return window['go']['backend']['App']['DbListVideos']();
}

export function DbUpdateVideo(arg1, arg2) {
  return window['go']['backend']['App']['DbUpdateVideo'](arg1, arg2);
}

export function GetActressPrimaryStudios(arg1) {
  return window['go']['backend']['App']['GetActressPrimaryStudios'](arg1);
}

export function GetStudioByCode(arg1) {
  return window['go']['backend']['App']['GetStudioByCode'](arg1);
}

export function GetStudiosByCodes(arg1) {
  return window['go']['backend']['App']['GetStudiosByCodes'](arg1);
}

export function GetOperation(arg1) {
  return window['go']['backend']['App']['GetOperation'](arg1);
}

export function GetPreferences() {
  return window['go']['backend']['App']['GetPreferences']();
}

export function IdentifyStudio(arg1) {
  return window['go']['backend']['App']['IdentifyStudio'](arg1);
}

export function ListOperations() {
  return window['go']['backend']['App']['ListOperations']();
}

export function ListStudios() {
  return window['go']['backend']['App']['ListStudios']();
}

export function MoveDir(arg1, arg2, arg3) {
  return window['go']['backend']['App']['MoveDir'](arg1, arg2, arg3);
}

export function MoveFile(arg1, arg2, arg3) {
  return window['go']['backend']['App']['MoveFile'](arg1, arg2, arg3);
}

export function PlanDirMergeMoves(arg1) {
  return window['go']['backend']['App']['PlanDirMergeMoves'](arg1);
}

export function PythonSearch(arg1) {
  return window['go']['backend']['App']['PythonSearch'](arg1);
}

export function ResetPreferences() {
  return window['go']['backend']['App']['ResetPreferences']();
}

export function RollbackLast() {
  return window['go']['backend']['App']['RollbackLast']();
}

export function RollbackOperation(arg1) {
  return window['go']['backend']['App']['RollbackOperation'](arg1);
}

export function ScanDirectory(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ScanDirectory'](arg1, arg2, arg3);
}

export function SelectDirectory(arg1) {
  return window['go']['backend']['App']['SelectDirectory'](arg1);
}

export function UpdatePreferences(arg1) {
  return window['go']['backend']['App']['UpdatePreferences'](arg1);
}
